### ISSUE TITLE
Access to Geth

### ISSUE THREAD

**Issue by jbunce** [ethersphere/helm-charts#1]
Please don't allow wildcard access from * to `rpcvhosts` or `wsorigins`. It only takes an accidental misconfiguration of a service to expose this to the outside world, and you could end up with a drained account. At a minimum you could consider limiting this to the ClusterIP range on your Kubernetes cluster.

**Comment by nonsense** [comment]
@jbunce good point! We are using Geth only for ENS resolution, so we hadn't considered if it is secure (which it is not) if people use it for other purposes.

Feel free to submit a PR, or we will update it when we get a chance.
